#!/usr/bin/env python3
"""Build a dated manuscript-facing inventory of external public-read opportunities.

This table is intentionally static and audit-oriented. It records the public
read studies that remain outside the current assembly-defined manuscript cohort
after the April 20, 2026 ENA scan, together with countries where the paired
Illumina public space is already close to saturation. The inventory is not
treated as a new denominator and does not imply that every listed study should
be merged into the current cohort without a separate read-first intake path.
"""

from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
FIGURE_DATA_PATH = ROOT / "manuscript" / "figure_data" / "external_public_read_opportunity_inventory.tsv"
SUPPLEMENTARY_PATH = (
    ROOT / "manuscript" / "supplementary" / "Supplementary_Table_56_External_Public_Read_Opportunity_Inventory.tsv"
)

FIELDNAMES = [
    "row_scope",
    "audit_accessed_date",
    "country_iso3",
    "country_name",
    "target_window_or_role",
    "current_retained_genomes",
    "opportunity_status",
    "priority_tier",
    "study_accession",
    "study_title",
    "data_class",
    "ena_browser_url",
    "first_public",
    "last_updated",
    "public_sample_accessions",
    "public_run_accessions",
    "collection_year_start",
    "collection_year_end",
    "absent_from_current_manifest",
    "recommended_intake_route",
    "notes",
]

ROWS = [
    {
        "row_scope": "country_summary",
        "audit_accessed_date": "2026-04-20",
        "country_iso3": "JPN",
        "country_name": "Japan",
        "target_window_or_role": "post-2012 PRN-free aP plus historical comparison",
        "current_retained_genomes": "87",
        "opportunity_status": "highest-value historical read-first backlog after direct contemporary intake",
        "priority_tier": "1",
        "study_accession": "",
        "study_title": "",
        "data_class": "country_summary",
        "ena_browser_url": "",
        "first_public": "",
        "last_updated": "",
        "public_sample_accessions": "",
        "public_run_accessions": "",
        "collection_year_start": "",
        "collection_year_end": "",
        "absent_from_current_manifest": "substantial residual headroom across five paired-Illumina WGS studies",
        "recommended_intake_route": "prioritize historical paired-Illumina read-first intake before new sensitivity analysis",
        "notes": (
            "Japan has already absorbed the highest-yield contemporary prefecture batches, but the largest remaining public "
            "expansion path is still historical: one 1982-2014 cohort, one broad NIID series spanning 2000-2025, and residual "
            "2024-2025 prefecture-level material remain outside the current manifest."
        ),
    },
    {
        "row_scope": "study_detail",
        "audit_accessed_date": "2026-04-20",
        "country_iso3": "JPN",
        "country_name": "Japan",
        "target_window_or_role": "historical pre- and early-aP baseline",
        "current_retained_genomes": "87",
        "opportunity_status": "read-first paired-Illumina intake candidate",
        "priority_tier": "1",
        "study_accession": "PRJEB18624",
        "study_title": "Bordetella pertussis population dynamics and phylogeny in Japan after adoption of acellular pertussis vaccines",
        "data_class": "genomic_paired_illumina_wgs",
        "ena_browser_url": "https://www.ebi.ac.uk/ena/browser/view/PRJEB18624",
        "first_public": "2018-02-13",
        "last_updated": "2017-10-27",
        "public_sample_accessions": "188",
        "public_run_accessions": "188",
        "collection_year_start": "1982",
        "collection_year_end": "2014",
        "absent_from_current_manifest": "188",
        "recommended_intake_route": "high-priority read-first isolate-WGS intake",
        "notes": "Best historical bridge for pre-2012 Japan and bounded support around PRN-free rollout.",
    },
    {
        "row_scope": "study_detail",
        "audit_accessed_date": "2026-04-20",
        "country_iso3": "JPN",
        "country_name": "Japan",
        "target_window_or_role": "national longitudinal follow-up",
        "current_retained_genomes": "87",
        "opportunity_status": "read-first paired-Illumina intake candidate",
        "priority_tier": "1",
        "study_accession": "PRJDB7578",
        "study_title": "WGS of Bordetella species",
        "data_class": "genomic_paired_illumina_wgs",
        "ena_browser_url": "https://www.ebi.ac.uk/ena/browser/view/PRJDB7578",
        "first_public": "2019-01-03",
        "last_updated": "2026-02-26",
        "public_sample_accessions": "134",
        "public_run_accessions": "134",
        "collection_year_start": "2000",
        "collection_year_end": "2025",
        "absent_from_current_manifest": "131",
        "recommended_intake_route": "high-priority read-first isolate-WGS intake",
        "notes": "Largest single Japanese longitudinal opportunity remaining outside the current manifest.",
    },
    {
        "row_scope": "study_detail",
        "audit_accessed_date": "2026-04-20",
        "country_iso3": "JPN",
        "country_name": "Japan",
        "target_window_or_role": "post-2012 PRN-free aP contemporary prefecture window",
        "current_retained_genomes": "87",
        "opportunity_status": "read-first paired-Illumina intake candidate",
        "priority_tier": "1",
        "study_accession": "PRJDB37898",
        "study_title": "Genome sequence of macrolide resistant Bordetella pertussis isolated in Okinawa, Japan",
        "data_class": "genomic_paired_illumina_wgs",
        "ena_browser_url": "https://www.ebi.ac.uk/ena/browser/view/PRJDB37898",
        "first_public": "2025-10-24",
        "last_updated": "2026-04-19",
        "public_sample_accessions": "43",
        "public_run_accessions": "43",
        "collection_year_start": "2025",
        "collection_year_end": "2025",
        "absent_from_current_manifest": "31",
        "recommended_intake_route": "high-priority read-first isolate-WGS intake",
        "notes": "Twelve Okinawa genomes were already integrated here; the remaining runs still strengthen the post-2012 PRN-free Japan window and add macrolide-resistance context.",
    },
    {
        "row_scope": "study_detail",
        "audit_accessed_date": "2026-04-20",
        "country_iso3": "JPN",
        "country_name": "Japan",
        "target_window_or_role": "post-2012 PRN-free aP contemporary prefecture window",
        "current_retained_genomes": "87",
        "opportunity_status": "read-first paired-Illumina intake candidate",
        "priority_tier": "1",
        "study_accession": "PRJDB34249",
        "study_title": "Epidemic mainly caused by macrolide-resistant mutation of Bordetella pertussis in Tottori, Japan",
        "data_class": "genomic_paired_illumina_wgs",
        "ena_browser_url": "https://www.ebi.ac.uk/ena/browser/view/PRJDB34249",
        "first_public": "2025-05-28",
        "last_updated": "2026-04-19",
        "public_sample_accessions": "16",
        "public_run_accessions": "16",
        "collection_year_start": "2024",
        "collection_year_end": "2025",
        "absent_from_current_manifest": "16",
        "recommended_intake_route": "high-priority read-first isolate-WGS intake",
        "notes": "Compact post-2012 Japan cohort with immediate value for PRN-free-era triangulation.",
    },
    {
        "row_scope": "study_detail",
        "audit_accessed_date": "2026-04-20",
        "country_iso3": "JPN",
        "country_name": "Japan",
        "target_window_or_role": "post-2012 PRN-free aP contemporary prefecture window",
        "current_retained_genomes": "87",
        "opportunity_status": "read-first paired-Illumina intake candidate",
        "priority_tier": "1",
        "study_accession": "PRJDB39872",
        "study_title": "Whole genome sequencing of Bordetella pertussis isolated in Shimane prefecture, Japan",
        "data_class": "genomic_paired_illumina_wgs",
        "ena_browser_url": "https://www.ebi.ac.uk/ena/browser/view/PRJDB39872",
        "first_public": "2026-01-17",
        "last_updated": "2026-04-19",
        "public_sample_accessions": "16",
        "public_run_accessions": "16",
        "collection_year_start": "2025",
        "collection_year_end": "2025",
        "absent_from_current_manifest": "4",
        "recommended_intake_route": "high-priority read-first isolate-WGS intake",
        "notes": "Twelve Shimane genomes were already integrated here; the residual runs remain useful for recent PRN-free-era Japan replication.",
    },
    {
        "row_scope": "country_summary",
        "audit_accessed_date": "2026-04-20",
        "country_iso3": "AUS",
        "country_name": "Australia",
        "target_window_or_role": "transition-era whole-cell to PRN-exposed aP comparison",
        "current_retained_genomes": "63",
        "opportunity_status": "residual split intake with isolate-WGS main branch and culture-independent sidecars",
        "priority_tier": "2",
        "study_accession": "",
        "study_title": "",
        "data_class": "country_summary",
        "ena_browser_url": "",
        "first_public": "",
        "last_updated": "",
        "public_sample_accessions": "",
        "public_run_accessions": "",
        "collection_year_start": "",
        "collection_year_end": "",
        "absent_from_current_manifest": "residual isolate-WGS cohorts plus newer mixed culture-independent projects",
        "recommended_intake_route": "retain isolate WGS as the main branch; keep capture and metagenomic studies as sidecars",
        "notes": (
            "Australia has already absorbed the highest-yield transition-era isolate-WGS runs targeted in this revision, but "
            "additional isolate-WGS material and newer targeted-capture, metagenomic-WGS, and amplicon studies can still "
            "strengthen the transition narrative without being forced into the main denominator."
        ),
    },
    {
        "row_scope": "study_detail",
        "audit_accessed_date": "2026-04-20",
        "country_iso3": "AUS",
        "country_name": "Australia",
        "target_window_or_role": "2008-2012 transition-era isolate WGS",
        "current_retained_genomes": "63",
        "opportunity_status": "read-first paired-Illumina intake candidate",
        "priority_tier": "2",
        "study_accession": "PRJNA562796",
        "study_title": "Bordetella pertussis Raw sequence reads",
        "data_class": "genomic_paired_illumina_wgs",
        "ena_browser_url": "https://www.ebi.ac.uk/ena/browser/view/PRJNA562796",
        "first_public": "2021-07-01",
        "last_updated": "2026-04-19",
        "public_sample_accessions": "284",
        "public_run_accessions": "284",
        "collection_year_start": "2008",
        "collection_year_end": "2012",
        "absent_from_current_manifest": "279",
        "recommended_intake_route": "high-priority read-first isolate-WGS intake",
        "notes": "Five Australia 2008-2012 genomes were already integrated here; the remainder is still the best public isolate-WGS bridge for the early transition period.",
    },
    {
        "row_scope": "study_detail",
        "audit_accessed_date": "2026-04-20",
        "country_iso3": "AUS",
        "country_name": "Australia",
        "target_window_or_role": "2013-2017 later transition and follow-up",
        "current_retained_genomes": "63",
        "opportunity_status": "read-first paired-Illumina intake candidate",
        "priority_tier": "2",
        "study_accession": "PRJNA432286",
        "study_title": "Molecular epidemiology of Bordetella pertussis, 2013 to 2017, Australia",
        "data_class": "genomic_paired_illumina_wgs",
        "ena_browser_url": "https://www.ebi.ac.uk/ena/browser/view/PRJNA432286",
        "first_public": "2019-03-01",
        "last_updated": "2026-04-19",
        "public_sample_accessions": "78",
        "public_run_accessions": "78",
        "collection_year_start": "2013",
        "collection_year_end": "2017",
        "absent_from_current_manifest": "73",
        "recommended_intake_route": "high-priority read-first isolate-WGS intake",
        "notes": "Five Australia 2013-2017 genomes were already integrated here; the remainder still extends the comparison beyond the early switch period with straightforward paired-Illumina isolate WGS.",
    },
    {
        "row_scope": "study_detail",
        "audit_accessed_date": "2026-04-20",
        "country_iso3": "AUS",
        "country_name": "Australia",
        "target_window_or_role": "recent direct-from-specimen and mixed isolate follow-up",
        "current_retained_genomes": "63",
        "opportunity_status": "sidecar candidate with partial isolate-WGS component",
        "priority_tier": "2",
        "study_accession": "PRJNA1199062",
        "study_title": "Bordetella pertussis Genome sequencing and assembly",
        "data_class": "mixed_genomic_wgs_and_targeted_capture",
        "ena_browser_url": "https://www.ebi.ac.uk/ena/browser/view/PRJNA1199062",
        "first_public": "2025-01-17",
        "last_updated": "2025-01-17",
        "public_sample_accessions": "154",
        "public_run_accessions": "192",
        "collection_year_start": "2012",
        "collection_year_end": "2024",
        "absent_from_current_manifest": "154",
        "recommended_intake_route": "split isolate-WGS rows into read-first intake and retain targeted-capture rows as a direct-from-specimen sidecar",
        "notes": "Contains 44 genomic-WGS runs plus 148 targeted-capture runs across 154 samples; useful, but not a single-caller denominator.",
    },
    {
        "row_scope": "study_detail",
        "audit_accessed_date": "2026-04-20",
        "country_iso3": "AUS",
        "country_name": "Australia",
        "target_window_or_role": "culture-independent surveillance sidecar",
        "current_retained_genomes": "63",
        "opportunity_status": "sidecar candidate only",
        "priority_tier": "3",
        "study_accession": "PRJNA1141746",
        "study_title": "Culture independent multiplex amplicon and metagenomic sequencing of B. pertussis",
        "data_class": "culture_independent_metagenomic_wgs_and_amplicon",
        "ena_browser_url": "https://www.ebi.ac.uk/ena/browser/view/PRJNA1141746",
        "first_public": "2024-09-28",
        "last_updated": "2024-09-28",
        "public_sample_accessions": "210",
        "public_run_accessions": "373",
        "collection_year_start": "2008",
        "collection_year_end": "2019",
        "absent_from_current_manifest": "210",
        "recommended_intake_route": "retain as a culture-independent sidecar rather than merge into isolate-defined denominators",
        "notes": "The study mixes 67 metagenomic-WGS runs with 306 amplicon runs; useful for opportunity mapping, not direct denominator replacement.",
    },
    {
        "row_scope": "country_summary",
        "audit_accessed_date": "2026-04-20",
        "country_iso3": "FIN",
        "country_name": "Finland",
        "target_window_or_role": "historical plus 2014-2016 aP-era comparator",
        "current_retained_genomes": "20",
        "opportunity_status": "partially realized formulation-clean read-first side branch",
        "priority_tier": "2",
        "study_accession": "",
        "study_title": "",
        "data_class": "country_summary",
        "ena_browser_url": "",
        "first_public": "",
        "last_updated": "",
        "public_sample_accessions": "",
        "public_run_accessions": "",
        "collection_year_start": "",
        "collection_year_end": "",
        "absent_from_current_manifest": "residual Europe-cohort and historical Finland material remains outside the current manifest",
        "recommended_intake_route": "continue as a formulation-clean read-first side branch",
        "notes": "Finland is no longer empty after direct intake, but it still offers a compact expansion path with cleaner product-context interpretation than many larger countries.",
    },
    {
        "row_scope": "study_detail",
        "audit_accessed_date": "2026-04-20",
        "country_iso3": "FIN",
        "country_name": "Finland",
        "target_window_or_role": "2014-2016 European collection",
        "current_retained_genomes": "20",
        "opportunity_status": "read-first paired-Illumina intake candidate",
        "priority_tier": "2",
        "study_accession": "PRJEB45681",
        "study_title": "Whole genome sequences of Bordetella isolates collected in Europe",
        "data_class": "genomic_paired_illumina_wgs",
        "ena_browser_url": "https://www.ebi.ac.uk/ena/browser/view/PRJEB45681",
        "first_public": "2022-01-13",
        "last_updated": "2022-01-13",
        "public_sample_accessions": "30",
        "public_run_accessions": "30",
        "collection_year_start": "2014",
        "collection_year_end": "2016",
        "absent_from_current_manifest": "24",
        "recommended_intake_route": "read-first isolate-WGS intake",
        "notes": "Six Finland genomes from the Europe 2014-2016 collection were already integrated here; the remaining sampled genomes remain outside the current manifest.",
    },
    {
        "row_scope": "study_detail",
        "audit_accessed_date": "2026-04-20",
        "country_iso3": "FIN",
        "country_name": "Finland",
        "target_window_or_role": "historical Finland context",
        "current_retained_genomes": "20",
        "opportunity_status": "read-first paired-Illumina intake candidate",
        "priority_tier": "2",
        "study_accession": "PRJNA262480",
        "study_title": "WGS sequencing of Bordetella pertussis",
        "data_class": "genomic_paired_illumina_wgs",
        "ena_browser_url": "https://www.ebi.ac.uk/ena/browser/view/PRJNA262480",
        "first_public": "2015-09-15",
        "last_updated": "2026-04-19",
        "public_sample_accessions": "11",
        "public_run_accessions": "11",
        "collection_year_start": "1957",
        "collection_year_end": "2008",
        "absent_from_current_manifest": "8",
        "recommended_intake_route": "read-first isolate-WGS intake",
        "notes": "Three historical Finland genomes were already integrated here; the remaining historical series complements the Europe 2014-2016 cohort.",
    },
    {
        "row_scope": "country_summary",
        "audit_accessed_date": "2026-04-21",
        "country_iso3": "CHN",
        "country_name": "China",
        "target_window_or_role": "late post-switch mixed-aP context branch",
        "current_retained_genomes": "856",
        "opportunity_status": "late-era read-first branch now integrated; remaining limitation is the missing pre-switch comparator",
        "priority_tier": "2",
        "study_accession": "",
        "study_title": "",
        "data_class": "country_summary",
        "ena_browser_url": "",
        "first_public": "",
        "last_updated": "",
        "public_sample_accessions": "",
        "public_run_accessions": "",
        "collection_year_start": "",
        "collection_year_end": "",
        "absent_from_current_manifest": "0 for the Guangzhou and Tianjin late-era batches listed below after direct read-first augmentation",
        "recommended_intake_route": "retain as late-era context and prioritize any future pre-2012 comparator material",
        "notes": (
            "China is not archive-poor: the current manifest retains 856 Chinese records, with 153 screen-relevant genomes "
            "PRN-interpretable in the selected-country screen. The informative rows still fall in the post-switch mixed-aP "
            "interval, so the Guangzhou and Tianjin read-first additions deepen that late-era branch but do not create the "
            "missing early comparison axis."
        ),
    },
    {
        "row_scope": "study_detail",
        "audit_accessed_date": "2026-04-21",
        "country_iso3": "CHN",
        "country_name": "China",
        "target_window_or_role": "2020-2024 Guangzhou late-era context expansion",
        "current_retained_genomes": "856",
        "opportunity_status": "integrated public_raw_read_assembly branch",
        "priority_tier": "2",
        "study_accession": "PRJNA1193776",
        "study_title": "Raw sequence reads of 62 Bordetella pertussis isolates in Guangdong, China",
        "data_class": "genomic_paired_illumina_wgs",
        "ena_browser_url": "https://www.ebi.ac.uk/ena/browser/view/PRJNA1193776",
        "first_public": "2025-03-06",
        "last_updated": "2026-04-19",
        "public_sample_accessions": "62",
        "public_run_accessions": "62",
        "collection_year_start": "2020",
        "collection_year_end": "2024",
        "absent_from_current_manifest": "0",
        "recommended_intake_route": "already incorporated through the read-first assembly path; retain as late China context",
        "notes": "Fully paired Illumina isolate WGS now incorporated through the direct public-read augmentation path; it strengthens the late China mixed-aP and macrolide-resistance context without adding an early comparator.",
    },
    {
        "row_scope": "study_detail",
        "audit_accessed_date": "2026-04-21",
        "country_iso3": "CHN",
        "country_name": "China",
        "target_window_or_role": "2023 Tianjin late-era context expansion",
        "current_retained_genomes": "856",
        "opportunity_status": "integrated public_raw_read_assembly branch",
        "priority_tier": "2",
        "study_accession": "PRJNA1297067",
        "study_title": "Whole genome sequencing of Bordetella pertussis in Tianjin, China",
        "data_class": "genomic_paired_short_read_wgs_dnbseq",
        "ena_browser_url": "https://www.ebi.ac.uk/ena/browser/view/PRJNA1297067",
        "first_public": "2025-07-28",
        "last_updated": "2025-07-28",
        "public_sample_accessions": "27",
        "public_run_accessions": "27",
        "collection_year_start": "2023",
        "collection_year_end": "2023",
        "absent_from_current_manifest": "0",
        "recommended_intake_route": "already incorporated through the paired short-read assembly path; retain as late China context",
        "notes": "Clean paired DNBSEQ genomic WGS cohort now incorporated through the same short-read augmentation path as Guangzhou; it has direct value for the 2023 China window but remains a late-era side branch.",
    },
    {
        "row_scope": "country_summary",
        "audit_accessed_date": "2026-04-20",
        "country_iso3": "GBR",
        "country_name": "Great Britain",
        "target_window_or_role": "epidemiologic primary-set country with modest mechanistic headroom",
        "current_retained_genomes": "35",
        "opportunity_status": "medium-priority read-first intake opportunity",
        "priority_tier": "3",
        "study_accession": "",
        "study_title": "",
        "data_class": "country_summary",
        "ena_browser_url": "",
        "first_public": "",
        "last_updated": "",
        "public_sample_accessions": "",
        "public_run_accessions": "",
        "collection_year_start": "",
        "collection_year_end": "",
        "absent_from_current_manifest": "30 paired-Illumina genomes in PRJEB45681",
        "recommended_intake_route": "read-first isolate-WGS intake; exclude non-genomic studies",
        "notes": "Great Britain remains estimable without new intake, but PRJEB45681 provides clean additional WGS coverage and an RNA-seq study should stay excluded.",
    },
    {
        "row_scope": "study_detail",
        "audit_accessed_date": "2026-04-20",
        "country_iso3": "GBR",
        "country_name": "Great Britain",
        "target_window_or_role": "2014-2016 European collection",
        "current_retained_genomes": "35",
        "opportunity_status": "read-first paired-Illumina intake candidate",
        "priority_tier": "3",
        "study_accession": "PRJEB45681",
        "study_title": "Whole genome sequences of Bordetella isolates collected in Europe",
        "data_class": "genomic_paired_illumina_wgs",
        "ena_browser_url": "https://www.ebi.ac.uk/ena/browser/view/PRJEB45681",
        "first_public": "2022-01-13",
        "last_updated": "2022-01-13",
        "public_sample_accessions": "30",
        "public_run_accessions": "30",
        "collection_year_start": "2014",
        "collection_year_end": "2016",
        "absent_from_current_manifest": "30",
        "recommended_intake_route": "read-first isolate-WGS intake",
        "notes": "The Britain subset in PRJEB45681 is entirely absent from the current manifest and can sharpen the bounded primary-set contrast.",
    },
    {
        "row_scope": "study_detail",
        "audit_accessed_date": "2026-04-20",
        "country_iso3": "GBR",
        "country_name": "Great Britain",
        "target_window_or_role": "explicitly excluded non-genomic study",
        "current_retained_genomes": "35",
        "opportunity_status": "excluded from genomic intake",
        "priority_tier": "exclude",
        "study_accession": "PRJNA972746",
        "study_title": "Bordetella pertussis strain:Tohama 1 BP536 Transcriptome or Gene expression",
        "data_class": "excluded_transcriptomic_rna_seq",
        "ena_browser_url": "https://www.ebi.ac.uk/ena/browser/view/PRJNA972746",
        "first_public": "2023-07-02",
        "last_updated": "2026-04-19",
        "public_sample_accessions": "12",
        "public_run_accessions": "12",
        "collection_year_start": "",
        "collection_year_end": "",
        "absent_from_current_manifest": "",
        "recommended_intake_route": "exclude from genomic denominator and from read-first intake",
        "notes": "Included here only to document explicit exclusion; all runs are transcriptomic RNA-seq rather than genomic WGS.",
    },
    {
        "row_scope": "country_summary",
        "audit_accessed_date": "2026-04-20",
        "country_iso3": "NZL",
        "country_name": "New Zealand",
        "target_window_or_role": "transition-country saturation check",
        "current_retained_genomes": "63",
        "opportunity_status": "near saturation for paired-Illumina public intake",
        "priority_tier": "4",
        "study_accession": "",
        "study_title": "",
        "data_class": "country_summary",
        "ena_browser_url": "",
        "first_public": "",
        "last_updated": "",
        "public_sample_accessions": "63",
        "public_run_accessions": "63",
        "collection_year_start": "",
        "collection_year_end": "",
        "absent_from_current_manifest": "0",
        "recommended_intake_route": "monitor only",
        "notes": "The April 2026 exact-country paired-Illumina WGS scan returned 63 sample accessions, all already represented in the current manifest.",
    },
    {
        "row_scope": "country_summary",
        "audit_accessed_date": "2026-04-20",
        "country_iso3": "ZAF",
        "country_name": "South Africa",
        "target_window_or_role": "bounded comparator saturation check",
        "current_retained_genomes": "32",
        "opportunity_status": "near saturation for paired-Illumina public intake",
        "priority_tier": "4",
        "study_accession": "",
        "study_title": "",
        "data_class": "country_summary",
        "ena_browser_url": "",
        "first_public": "",
        "last_updated": "",
        "public_sample_accessions": "32",
        "public_run_accessions": "32",
        "collection_year_start": "",
        "collection_year_end": "",
        "absent_from_current_manifest": "0",
        "recommended_intake_route": "monitor only",
        "notes": "The April 2026 exact-country paired-Illumina WGS scan found no additional South African sample accession absent from the current manifest.",
    },
    {
        "row_scope": "country_summary",
        "audit_accessed_date": "2026-04-20",
        "country_iso3": "BRA",
        "country_name": "Brazil",
        "target_window_or_role": "long-wP public-data availability check",
        "current_retained_genomes": "13",
        "opportunity_status": "public paired-Illumina additions remain sparse",
        "priority_tier": "4",
        "study_accession": "",
        "study_title": "",
        "data_class": "country_summary",
        "ena_browser_url": "",
        "first_public": "",
        "last_updated": "",
        "public_sample_accessions": "1",
        "public_run_accessions": "1",
        "collection_year_start": "",
        "collection_year_end": "",
        "absent_from_current_manifest": "0",
        "recommended_intake_route": "no immediate read-first expansion available",
        "notes": "The April 2026 exact-country paired-Illumina WGS scan returned one sample accession, already represented; additional public wP context remains sparse.",
    },
    {
        "row_scope": "country_summary",
        "audit_accessed_date": "2026-04-20",
        "country_iso3": "IND",
        "country_name": "India",
        "target_window_or_role": "long-wP public-data availability check",
        "current_retained_genomes": "11",
        "opportunity_status": "public paired-Illumina additions remain sparse",
        "priority_tier": "4",
        "study_accession": "",
        "study_title": "",
        "data_class": "country_summary",
        "ena_browser_url": "",
        "first_public": "",
        "last_updated": "",
        "public_sample_accessions": "2",
        "public_run_accessions": "2",
        "collection_year_start": "",
        "collection_year_end": "",
        "absent_from_current_manifest": "0",
        "recommended_intake_route": "no immediate read-first expansion available",
        "notes": "The April 2026 exact-country paired-Illumina WGS scan returned two Indian sample accessions, both already represented in the current manifest.",
    },
    {
        "row_scope": "country_summary",
        "audit_accessed_date": "2026-04-20",
        "country_iso3": "USA",
        "country_name": "United States",
        "target_window_or_role": "post-freeze incremental update check",
        "current_retained_genomes": "958",
        "opportunity_status": "deprioritized incremental intake",
        "priority_tier": "4",
        "study_accession": "",
        "study_title": "",
        "data_class": "country_summary",
        "ena_browser_url": "",
        "first_public": "",
        "last_updated": "",
        "public_sample_accessions": "",
        "public_run_accessions": "",
        "collection_year_start": "",
        "collection_year_end": "",
        "absent_from_current_manifest": "6 post-freeze paired-Illumina runs",
        "recommended_intake_route": "do not prioritize for the main revision",
        "notes": "New USA additions exist, but they would mostly reinforce a study-amplified signal that is already explicitly caveated in the manuscript.",
    },
    {
        "row_scope": "study_detail",
        "audit_accessed_date": "2026-04-20",
        "country_iso3": "USA",
        "country_name": "United States",
        "target_window_or_role": "post-freeze incremental update",
        "current_retained_genomes": "958",
        "opportunity_status": "deprioritized incremental intake",
        "priority_tier": "4",
        "study_accession": "PRJNA279196",
        "study_title": "Whole genome sequencing of Bordetella pertussis geographic and temporal diversity in the United States",
        "data_class": "genomic_paired_illumina_wgs",
        "ena_browser_url": "https://www.ebi.ac.uk/ena/browser/view/PRJNA279196",
        "first_public": "2026-04-12",
        "last_updated": "2026-04-19",
        "public_sample_accessions": "6",
        "public_run_accessions": "6",
        "collection_year_start": "2019",
        "collection_year_end": "2019",
        "absent_from_current_manifest": "6",
        "recommended_intake_route": "optional late freeze add-on only",
        "notes": "All six runs are USA:IL 2019 paired-Illumina WGS and are not a priority because they intensify an already dominant USA study block.",
    },
]


def write_tsv(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=FIELDNAMES, delimiter="\t")
        writer.writeheader()
        for row in ROWS:
            writer.writerow({field: row.get(field, "") for field in FIELDNAMES})


def main() -> None:
    write_tsv(FIGURE_DATA_PATH)
    write_tsv(SUPPLEMENTARY_PATH)


if __name__ == "__main__":
    main()
